#ifndef DEVELOPER_JOYOFENERGY_C_CONFIGURATION_H
#define DEVELOPER_JOYOFENERGY_C_CONFIGURATION_H

#include <assert.h>

#define DR_EVILS_DARK_ENERGY_ENERGY_SUPPLIER "Dr Evil's Dark Energy"
#define THE_GREEN_ECO_ENERGY_SUPPLIER "The Green Eco"
#define POWER_FOR_EVERYONE_ENERGY_SUPPLIER "Power for Everyone"

#define MOST_EVIL_PRICE_PLAN_ID "price-plan-0"
#define RENEWABLES_PRICE_PLAN_ID "price-plan-1"
#define STANDARD_PRICE_PLAN_ID "price-plan-2"

#define MAX_ELECTRICITY_READING_COUNT 1024

#define READING_STORE_PERIOD_MINUTES 15
#define READING_STORE_PERIOD_SECONDS (READING_STORE_PERIOD_MINUTES * 60)

#endif  // DEVELOPER_JOYOFENERGY_C_CONFIGURATION_H
